In the file **marks.csv** you will find the data of several students: Name, Surname, Honors, Birth Year, and a list of grades.

Create **one** file `data.pdf`, where each of the students will be presented on a separate page:

```
[Student/Honors student - choose one, based on the "Honors" column] Name - header.
Year of birth - normal text

Marks: - smaller header
Language Arts - 6
Second Language English - 5
...
```

In [1]:
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import pandas as pd

# Read the CSV file
df = pd.read_csv('marks.csv')


# Create a new column 'LOC' by concatenating 'name' and 'surname'
df['LOC'] = df['Name'] + ' ' + df['Surname']


# Create a PDF file
pdf_file = 'data.pdf'

df

,Name,Surname,Honors,Birth Year,Language Arts,Second Language English,Second Language German,Maths,Chemistry,Physics,Biology,History,Geography,LOC
0,Carol,Neweek,Y,1990,5,6,5,3,4,4,5,5,4,Carol Neweek
1,Martin,Cheapman,N,1990,3,4,3,6,5,5,3,3,5,Martin Cheapman
2,Charlie,Kovacs,N,1993,5,5,5,4,3,3,4,5,4,Charlie Kovacs
3,Agnes,Hale,Y,1993,5,5,4,6,6,5,3,5,4,Agnes Hale
4,Mary Jane,Tomala,N,1993,4,5,4,6,4,6,4,4,3,Mary Jane Tomala

This line sets the name of the output PDF file.
Define a function to create PDF for each student

In [3]:
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

def create_student_page(c, student_data):
    # Format data
    name = student_data['Name']
    surname = student_data['Surname']
    honors = student_data['Honors']
    birth_year = student_data['Birth Year']
    grades = student_data.drop(['Name', 'Surname', 'Honors', 'Birth Year']).to_dict()
    
    # Determine header based on Honors column
    if honors == 'Y':
        header = f"Honors Student - {name} {surname}"
    else:
        header = f"Student - {name} {surname}"
    
    # Set up content
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 750, header)
    
    c.setFont("Helvetica", 12)
    c.drawString(100, 730, f"Year of birth: {birth_year}")
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(100, 700, "Marks:")
    
    c.setFont("Helvetica", 12)
    y_position = 680
    for subject, grade in grades.items():
        c.drawString(120, y_position, f"{subject}: {grade}")
        y_position -= 20

    c.showPage()  # Move to the next page

def main():
    # Read CSV file into a pandas DataFrame
    df = pd.read_csv('marks.csv')
    
    # Create a PDF
    c = canvas.Canvas("data.pdf", pagesize=letter)
    
    # Iterate over each student row
    for index, row in df.iterrows():
        create_student_page(c, row)
    
    c.save()

if __name__ == "__main__":
    main()